### ISSUE TITLE
Version Handler 

### ISSUE THREAD

**Issue by ZyC0R3** [ZyC0R3/Rita#21]
In 2 location the bot version is harcoded, i would like this to be called, 

in `src/commands/stats.js` the version is called by
```var version = `**\`${data.config.version}\`**`;```
but in 
`src/core/status.js` it is hardcoded using
```const botVersion = "1.1.2";``` 
and in `src/events.js` its just the status of the bot, This can be removed if it cant be changed

**Comment by ZyC0R3** [comment]
https://stackoverflow.com/questions/9153571/is-there-a-way-to-get-version-from-package-json-in-nodejs-code

**Comment by wdaniel1985** [comment]
Assign this issue to me and I will look into it when I am back
