### ISSUE TITLE
V: ID:41e90326-5a60-4440-9d7a-ec915d2a7235

### ISSUE THREAD

**Issue by ZyC0R3** [ZyC0R3/Rita#34]
**Record Below Activity Feed > Build Log or Failed Version Reason**
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  9.0.0
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 9.0.0...
       Downloading and installing node 9.0.0...
       Using default npm version: 5.5.1
       
-----> Restoring cache
       - node_modules
       
-----> Installing dependencies
       Installing node modules (package.json + package-lock)
       added 68 packages in 5.272s
       
-----> Build
       Running build
       
       > Rita@1.1.6 build /tmp/build_68e43e3aa65800ef769e3d4f80811aac
       > gulp build
       
/tmp/build_68e43e3aa65800ef769e3d4f80811aac/gulpfile.js:23
gulp.task("default", gulp.parallel("lint", "compress"));
                          ^
TypeError: gulp.parallel is not a function
    at Object.<anonymous> (/tmp/build_68e43e3aa65800ef769e3d4f80811aac/gulpfile.js:23:27)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/tmp/build_68e43e3aa65800ef769e3d4f80811aac/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/tmp/build_68e43e3aa65800ef769e3d4f80811aac/node_modules/liftoff/index.js:198:16)
    at module.exports (/tmp/build_68e43e3aa65800ef769e3d4f80811aac/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/tmp/build_68e43e3aa65800ef769e3d4f80811aac/node_modules/liftoff/index.js:190:9)
    at /tmp/build_68e43e3aa65800ef769e3d4f80811aac/node_modules/liftoff/index.js:164:9
    at /tmp/build_68e43e3aa65800ef769e3d4f80811aac/node_modules/v8flags/index.js:93:14
    at FSReqWrap.oncomplete (fs.js:149:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Rita@1.1.6 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Rita@1.1.6 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.cFXC4/_logs/2019-07-27T01_45_24_846Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by ZyC0R3** [comment]
Changes to Gulpfile.js broke this build 

TypeError: gulp.parallel is not a function

It was

``` 
gulp.task("default", ["lint", "compress"]);
gulp.task("build", ["lint", "compress"]);
gulp.watch("src/**/*.js", ["default"]);
```
but what changed to 
```
gulp.task("default", gulp.parallel("lint", "compress"));
gulp.task("build", gulp.parallel("lint", "compress"));
gulp.watch("src/**/*.js", gulp.series("default"));
```

**Comment by JShep89** [comment]
The gulp file requires all gulp related dependencies to be upgraded to their latest versions

**Comment by ZyC0R3** [comment]
can you commit to test branch to i can pull and build

**Comment by JShep89** [comment]
Yea will do as soon as I get home
