### ISSUE TITLE
translate.tasks.js

### ISSUE THREAD

**Issue by ZyC0R3** [ZyC0R3/Rita#5]
**Details of deployment log**
src/commands/translate.tasks.js

- [x] 4:7 warning '_logger' is assigned a value but never used no-unused-vars
- [x] 85:40  warning  'origin' is defined but never used            no-unused-vars
- [x] 85:48  warning  'dest' is defined but never used              no-unused-vars
- [x] 85:54 warning 'destDisplay' is defined but never used no-unused-vars
- [x] 98:51 warning Trailing spaces not allowed no-trailing-spaces
- [x] 105:96 warning Unexpected string concatenation of literals no-useless-concat
- [x] 105:151 warning Missing semicolon semi
- [x] 106:1 warning Expected indentation of 6 spaces but found 1 tab indent
- [x] 108:67 warning Missing semicolon semi

**Comment by JShep89** [comment]
Fixed these errors:
98:51 warning Trailing spaces not allowed no-trailing-spaces
105:151 warning Missing semicolon semi
106:1 warning Expected indentation of 6 spaces but found 1 tab indent
108:67 warning Missing semicolon semi
Pull from my fork(jshep89)

**Comment by ZyC0R3** [comment]
#66 Fixed with eslint file change.
