### ISSUE TITLE
args.js

### ISSUE THREAD

**Issue by ZyC0R3** [ZyC0R3/Rita#8]
**Details of deployment log**
src/commands/args.js

- [x] 161:25 warning Function has a complexity of 7 complexity
- [x] 243:18 warning Do not access Object.prototype method 'hasOwnProperty' from target object no-prototype-builtins
- [x] 242:1  warning  Trailing spaces not allowed  no-trailing-spaces

**Comment by JShep89** [comment]
fixed by editing the complexity limit in .eslint.json file. pull updated one from my fork(Jshep89)
